name: Pull Request Check
on:
  pull_request:
    branches:
      - main

jobs:
  setup-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch PR Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Environment Initialization
        uses: ./.github/composite-actions/env-initialization

  validate:
    runs-on: ubuntu-latest
    needs: [setup-cache]
    steps:
      - name: Fetch PR Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Environment Initialization with no install
        uses: ./.github/composite-actions/env-initialization
        with:
          allow-install: 'false'

      - name: Run Validation
        # This environment is required for the validation step.
        # It contains only placeholder values. Check .env.example for the required variables.
        env:
          SELF_DOMAIN: http://localhost:3000
          AUTH_SECRET: some.auth.secret.value
          AUTH_GOOGLE_ID: some.google.id.value
          AUTH_GOOGLE_SECRET: some.google.secret.value
          MONGO_CONNECTION_URI: mongodb://mongo-srv-url
          BISHAL_SWING_DB: some.bishal.db.value
          WHATSAPP_SENDER_PHONE_NUMBER_ID: 123456789
          WHATSAPP_AUTHORIZATION_TOKEN: some.token.value
        run: |
          pnpm run validate

  test:
    runs-on: ubuntu-latest
    needs: [setup-cache]
    steps:
      - name: Fetch PR Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Environment Initialization with no install
        uses: ./.github/composite-actions/env-initialization
        with:
          allow-install: 'false'

      - name: Run Tests
        run: |
          pnpm run test

  done:
    runs-on: ubuntu-latest
    needs: [test, validate]
    if: always()
    steps:
      - name: Check for failures
        if: ${{  needs.validate.result == 'failure' || needs.test.result == 'failure' }}
        run: |
          echo "Failure on checks"
          exit 1
